title: Homepage | Nico Lueg
author: Nico Lueg
email: nicolueg@gmx.de
description: > # this means to ignore newlines until "show_exerpts:"
  My name is Nico Lueg, I am an IT-Consultant and programming enthusiast from Germany. 
  I want to share my experiences that I made while developing.
show_excerpts: true # set to true to show excerpts on the homepage

url: https://www.nicolueg.com

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass
 
remote_theme: thelehhman/plainwhite-jekyll  
google_site_verification: FNaaXWwsnfU4VXhQ8kaUQXERO5Lv0k5cUQsd4LdK5UU

plainwhite:
  name: Nico Lueg
  tagline: > 
        IT-Consultant.
  date_format: "%b %-d, %Y"
  sitemap: true # set to true to generate sitemap.xml content
  disqus_shortname: nicolueg
  
  analytics_id: 'UA-146687582-1'

  # generate social links in footer
  social_links:
    github:  nlueg
    xing: Nico_Lueg3
    rss: rss
    
scholar:
  style: bibliography/ieee.csl
  locale: en

  sort_by: none
  order: ascending

  group_by: none
  group_order: ascending

  source: bibliography
  bibliography: bibliography.bib
  bibliography_template: "{{reference}}"

  replace_strings: true
  join_strings:    true

  use_raw_bibtex_entry: false

  bibtex_filters:
    - latex

  details_dir:    bibliography
  details_layout: bibtex.html
  details_link:   Details

  query: "@*"
  
  bibliography_list_tag: ol
  parse_block_html: true
 
algolia:
  application_id: 1TW92TYN2U
  index_name:     my_blog
  search_only_api_key: 60be79fb752722f166d1c69a7b11932b

pagination:
  enabled: true
  per_page: 10
  permalink: '/page/:num/'
  limit: 0
  title: ':title - Page :num'
  
extlinks:
  attributes: {rel: noopener noreferrer, target: _blank}

feed:
  title: Homepage RSS | Nico Lueg

plugins:
  - jekyll-scholar
  - jekyll-seo-tag
  - jekyll-feed
  - jemoji # Smileys: https://github.com/jekyll/jemoji
  - jekyll-toc
  - jekyll-paginate-v2
  - jekyll-extlinks